[project]
name = "mvp-rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "SathisKasi", email = "sathismoorthykumar@gmail.com" }
]
requires-python = ">=3.10"
dependencies = [
    "langchain-community",
    "langchain-google-genai",
    "langchain-groq",
    "langchain>=1.4.3",
    "pypdf",
    "python-dotenv",
    "langchain_chroma"
]

[project.scripts]
mvp-rag = "mvp_rag:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"

[tool.uv]
constraint-dependencies = ["onnxruntime<1.24.0; python_full_version < '3.11'"]
